spring:
  data:
      mongodb:
        user: admin
        password: admin
        uri: mongodb://localhost:27017/bloodbank

codeAvengers:
  app:       
     jwtSecret: codeAvengersSecretKey
     jwtExpirationMs: 86400000

